profile: development
replicaCount: 1
image:
  repo: registry.cn-hangzhou.aliyuncs.com/yjyp/{{group.name}}-{{service.code}}
  pullPolicy: IfNotPresent
imagePullSecrets: yjyp-image-pull-secret

readiness:
  enabled: true
  initialDelaySeconds: 60

liveness:
  enabled: true
  initialDelaySeconds: 60

hpa:
  enabled: true
  min: 1
  max: 1
  threshold: 80
log:
  enabled: true

persistence:
  enabled: false

service:
  name: {{service.code}}
  enabled: true
  type: ClusterIP
  port: 80
  targetPort: 8080
ingress:
  enabled: false

resources:
  limits:
    cpu: 500m
    memory: 500M
  requests:
    cpu: 200m
    memory: 200M
