{{- if .Values.hpa.enabled -}}
apiVersion: autoscaling/v2beta1
kind: HorizontalPodAutoscaler
metadata:
  name: {{ .Release.Name }}
  labels:
{{ include "service.labels.standard" . | indent 4 }}
{{ include "service.labels.release" . | indent 4 }}
spec:
  minReplicas: {{ .Values.hpa.min | default 1 }}
  maxReplicas: {{ .Values.hpa.max | default 3 }}
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ .Release.Name }}
  metrics:
  - type: Resource
    resource:
      name: {{ .Values.hpa.scaleOn | default "cpu" }}
      targetAverageUtilization: {{ .Values.hpa.threshold | default 80 }}
{{- end }}