{{- if .Values.service.enabled -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.service.name | default .Release.Name }}
  labels:
{{ include "service.labels.release" . | indent 4 }}
{{ include "service.labels.standard" . | indent 4 }}
spec:
  type: {{ .Values.service.type | default "ClusterIP" }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort | default 8000 }}
      protocol: TCP
      name: http
      {{- if .Values.service.nodePort }}
      nodePort: {{ .Values.service.nodePort }}
      {{- end }}
  selector:
{{ include "service.labels.release" . | indent 4 }}
{{- end }}